annotations:
  images: |
    - name: opensearch
      image: docker.io/raymondstrose/opensearch:3.0.0
    #- name: opensearch-dashboards
    #  image: docker.io/raymondstrose/opensearch-dashboards:3.2.0-debian-12-r0
    - name: os-shell
      image: docker.io/raymondstrose/ubuntu:24.04
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 3.0.0
#dependencies:
#- name: common
#  repository: oci://registry-1.docker.io/bitnamicharts
#  tags:
#  - bitnami-common
#  version: 2.x.x
description: OpenSearch is a scalable open-source solution for search, analytics,
  and observability. Features full-text queries, natural language processing, custom
  dictionaries, amongst others.
#home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/opensearch/img/opensearch-stack-220x234.png
keywords:
- opensearch
maintainers:
- name: Raymond St.Rose
name: opensearch
#sources:
#- https://github.com/bitnami/charts/tree/main/bitnami/opensearch
version: 1.0.0
